steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south2-docker.pkg.dev/gcp-cicd-demo-493513/pyapprepo-artifact/pyappimage:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south2-docker.pkg.dev/gcp-cicd-demo-493513/pyapprepo-artifact/pyappimage:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'pyapp'
    - '--image'
    - 'asia-south2-docker.pkg.dev/gcp-cicd-demo-493513/pyapprepo-artifact/pyappimage:latest'
    - '--region'
    - 'asia-south2'
    - '--no-invoker-iam-check'
options:
  logging: CLOUD_LOGGING_ONLY